#!/usr/bin/env node
/**
 * Local Development Setup Script
 * 
 * RESPONSIBILITY: Initialize local development environment for Trust Census System
 * 
 * This script:
 * 1. Creates .env file with development credentials
 * 2. Creates database and roles
 * 3. Runs migrations in correct order
 * 4. Verifies database role permissions
 * 5. Creates test users for each role
 * 
 * MUST:
 * - Use separate database users for each role
 * - Verify separation of powers after setup
 * - Fail if any security constraint is violated
 * 
 * MUST NEVER:
 * - Run in production
 * - Use shared credentials
 * - Skip permission verification
 */

import { writeFileSync, existsSync, readFileSync } from 'fs';
import { execSync, spawn } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import pg from 'pg';

const { Pool, Client } = pg;
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

// Development credentials generator
// Generates random passwords for local development
import crypto from 'crypto';

function generatePassword() {
  return crypto.randomBytes(16).toString('hex');
}

function generateJwtSecret() {
  return crypto.randomBytes(32).toString('hex');
}

// Development credentials (regenerated each setup)
const DEV_CONFIG = {
  DB_HOST: process.env.DB_HOST || 'localhost',
  DB_PORT: process.env.DB_PORT || '5432',
  DB_NAME: process.env.DB_NAME || 'trust_census',
  DB_USER: process.env.DB_USER || 'postgres',
  DB_PASSWORD: process.env.DB_PASSWORD || 'postgres',
  
  // Role credentials - generated if not in environment
  DB_API_WRITER_USER: 'api_writer',
  DB_API_WRITER_PASSWORD: process.env.DB_API_WRITER_PASSWORD || generatePassword(),
  
  DB_AUDIT_WRITER_USER: 'audit_writer',
  DB_AUDIT_WRITER_PASSWORD: process.env.DB_AUDIT_WRITER_PASSWORD || generatePassword(),
  
  DB_AGGREGATION_WORKER_USER: 'aggregation_worker',
  DB_AGGREGATION_WORKER_PASSWORD: process.env.DB_AGGREGATION_WORKER_PASSWORD || generatePassword(),
  
  DB_ANALYTICS_READER_USER: 'analytics_reader',
  DB_ANALYTICS_READER_PASSWORD: process.env.DB_ANALYTICS_READER_PASSWORD || generatePassword(),
  
  DB_SUPERVISOR_READER_USER: 'supervisor_reader',
  DB_SUPERVISOR_READER_PASSWORD: process.env.DB_SUPERVISOR_READER_PASSWORD || generatePassword(),
  
  JWT_SECRET: process.env.JWT_SECRET || generateJwtSecret(),
  JWT_EXPIRY: '24h',
  PORT: '3000',
  HOST: '0.0.0.0',
  NODE_ENV: 'development',
  RATE_LIMIT_MAX: '100',
  RATE_LIMIT_TIME_WINDOW: '60000',
};

console.log('='.repeat(70));
console.log('Trust-First Caste Census Management System - Local Setup');
console.log('='.repeat(70));
console.log('');
console.log('⚠️  WARNING: This script is for LOCAL DEVELOPMENT ONLY');
console.log('⚠️  DO NOT use these credentials in production');
console.log('');

// Step 1: Create .env file
console.log('Step 1: Creating .env file...');
const envContent = Object.entries(DEV_CONFIG)
  .map(([key, value]) => `${key}=${value}`)
  .join('\n');

const envPath = join(projectRoot, '.env');
try {
  writeFileSync(envPath, `# Trust Census Local Development Configuration
# Generated by setup-local.js
# DO NOT USE IN PRODUCTION

${envContent}
`);
  console.log('✅ .env file created');
} catch (err) {
  console.log('⚠️  Could not write .env file (may be gitignored)');
  console.log('   Please create .env manually with the following content:');
  console.log('');
  console.log(envContent);
  console.log('');
}

// Load environment
Object.assign(process.env, DEV_CONFIG);

// Step 2: Check PostgreSQL connection
console.log('');
console.log('Step 2: Checking PostgreSQL connection...');

async function checkPostgres() {
  const client = new Client({
    host: DEV_CONFIG.DB_HOST,
    port: parseInt(DEV_CONFIG.DB_PORT),
    user: DEV_CONFIG.DB_USER,
    password: DEV_CONFIG.DB_PASSWORD,
    database: 'postgres', // Connect to default database first
  });

  try {
    await client.connect();
    console.log('✅ PostgreSQL connection successful');
    
    // Check if database exists
    const result = await client.query(
      "SELECT 1 FROM pg_database WHERE datname = $1",
      [DEV_CONFIG.DB_NAME]
    );
    
    if (result.rows.length === 0) {
      console.log(`   Creating database: ${DEV_CONFIG.DB_NAME}...`);
      await client.query(`CREATE DATABASE ${DEV_CONFIG.DB_NAME}`);
      console.log('✅ Database created');
    } else {
      console.log(`✅ Database ${DEV_CONFIG.DB_NAME} exists`);
    }
    
    await client.end();
    return true;
  } catch (err) {
    console.log('❌ PostgreSQL connection failed:', err.message);
    console.log('');
    console.log('Please ensure PostgreSQL is running and accessible.');
    console.log('You can start PostgreSQL using Docker:');
    console.log('');
    console.log('  docker run -d --name trust-census-postgres \\');
    console.log('    -e POSTGRES_PASSWORD=postgres \\');
    console.log('    -p 5432:5432 \\');
    console.log('    postgres:16-alpine');
    console.log('');
    return false;
  }
}

// Step 3: Run migrations
async function runMigrations() {
  console.log('');
  console.log('Step 3: Running database migrations...');
  
  const client = new Client({
    host: DEV_CONFIG.DB_HOST,
    port: parseInt(DEV_CONFIG.DB_PORT),
    user: DEV_CONFIG.DB_USER,
    password: DEV_CONFIG.DB_PASSWORD,
    database: DEV_CONFIG.DB_NAME,
  });

  await client.connect();

  const migrations = [
    '001_update_roles.sql',
    '002_database_roles.sql',
    '003_user_scopes.sql',
    '004_consent_model.sql',
    '005_micro_aggregates_schema.sql',
    '006_macro_aggregates_schema.sql',
  ];

  for (const migration of migrations) {
    const migrationPath = join(projectRoot, 'src', 'db', 'migrations', migration);
    
    if (!existsSync(migrationPath)) {
      console.log(`⚠️  Migration not found: ${migration}`);
      continue;
    }

    console.log(`   Running ${migration}...`);
    
    try {
      const sql = readFileSync(migrationPath, 'utf-8');
      await client.query(sql);
      console.log(`   ✅ ${migration} completed`);
    } catch (err) {
      // Some errors are expected (e.g., "role already exists")
      if (err.message.includes('already exists') || err.message.includes('duplicate')) {
        console.log(`   ⚠️  ${migration}: ${err.message.split('\n')[0]}`);
      } else {
        console.log(`   ❌ ${migration} failed: ${err.message}`);
      }
    }
  }

  await client.end();
  console.log('✅ Migrations complete');
}

// Step 4: Verify role permissions
async function verifyRolePermissions() {
  console.log('');
  console.log('Step 4: Verifying database role permissions...');
  
  const results = {};

  // Test api_writer
  console.log('   Testing api_writer role...');
  try {
    const pool = new Pool({
      host: DEV_CONFIG.DB_HOST,
      port: parseInt(DEV_CONFIG.DB_PORT),
      database: DEV_CONFIG.DB_NAME,
      user: DEV_CONFIG.DB_API_WRITER_USER,
      password: DEV_CONFIG.DB_API_WRITER_PASSWORD,
    });
    
    await pool.query('SELECT 1');
    results.apiWriter = { connected: true };
    
    // Verify cannot SELECT from census_submissions (L1 is write-only)
    try {
      await pool.query('SELECT id FROM census_submissions LIMIT 1');
      results.apiWriter.canReadL1 = true;
      console.log('   ⚠️  api_writer CAN read L1 (may be expected if table is empty)');
    } catch (e) {
      results.apiWriter.canReadL1 = false;
      console.log('   ✅ api_writer cannot read L1 (correct)');
    }
    
    await pool.end();
  } catch (e) {
    results.apiWriter = { connected: false, error: e.message };
    console.log(`   ❌ api_writer: ${e.message}`);
  }

  // Test audit_writer
  console.log('   Testing audit_writer role...');
  try {
    const pool = new Pool({
      host: DEV_CONFIG.DB_HOST,
      port: parseInt(DEV_CONFIG.DB_PORT),
      database: DEV_CONFIG.DB_NAME,
      user: DEV_CONFIG.DB_AUDIT_WRITER_USER,
      password: DEV_CONFIG.DB_AUDIT_WRITER_PASSWORD,
    });
    
    await pool.query('SELECT 1');
    results.auditWriter = { connected: true };
    console.log('   ✅ audit_writer connected');
    
    await pool.end();
  } catch (e) {
    results.auditWriter = { connected: false, error: e.message };
    console.log(`   ❌ audit_writer: ${e.message}`);
  }

  // Test aggregation_worker
  console.log('   Testing aggregation_worker role...');
  try {
    const pool = new Pool({
      host: DEV_CONFIG.DB_HOST,
      port: parseInt(DEV_CONFIG.DB_PORT),
      database: DEV_CONFIG.DB_NAME,
      user: DEV_CONFIG.DB_AGGREGATION_WORKER_USER,
      password: DEV_CONFIG.DB_AGGREGATION_WORKER_PASSWORD,
    });
    
    await pool.query('SELECT 1');
    results.aggregationWorker = { connected: true };
    console.log('   ✅ aggregation_worker connected');
    
    await pool.end();
  } catch (e) {
    results.aggregationWorker = { connected: false, error: e.message };
    console.log(`   ❌ aggregation_worker: ${e.message}`);
  }

  // Test analytics_reader
  console.log('   Testing analytics_reader role...');
  try {
    const pool = new Pool({
      host: DEV_CONFIG.DB_HOST,
      port: parseInt(DEV_CONFIG.DB_PORT),
      database: DEV_CONFIG.DB_NAME,
      user: DEV_CONFIG.DB_ANALYTICS_READER_USER,
      password: DEV_CONFIG.DB_ANALYTICS_READER_PASSWORD,
    });
    
    await pool.query('SELECT 1');
    results.analyticsReader = { connected: true };
    console.log('   ✅ analytics_reader connected');
    
    await pool.end();
  } catch (e) {
    results.analyticsReader = { connected: false, error: e.message };
    console.log(`   ❌ analytics_reader: ${e.message}`);
  }

  // Test supervisor_reader
  console.log('   Testing supervisor_reader role...');
  try {
    const pool = new Pool({
      host: DEV_CONFIG.DB_HOST,
      port: parseInt(DEV_CONFIG.DB_PORT),
      database: DEV_CONFIG.DB_NAME,
      user: DEV_CONFIG.DB_SUPERVISOR_READER_USER,
      password: DEV_CONFIG.DB_SUPERVISOR_READER_PASSWORD,
    });
    
    await pool.query('SELECT 1');
    results.supervisorReader = { connected: true };
    console.log('   ✅ supervisor_reader connected');
    
    await pool.end();
  } catch (e) {
    results.supervisorReader = { connected: false, error: e.message };
    console.log(`   ❌ supervisor_reader: ${e.message}`);
  }

  return results;
}

// Step 5: Verify triggers exist
async function verifyTriggers() {
  console.log('');
  console.log('Step 5: Verifying append-only triggers...');
  
  const client = new Client({
    host: DEV_CONFIG.DB_HOST,
    port: parseInt(DEV_CONFIG.DB_PORT),
    user: DEV_CONFIG.DB_USER,
    password: DEV_CONFIG.DB_PASSWORD,
    database: DEV_CONFIG.DB_NAME,
  });

  await client.connect();

  const triggerQuery = `
    SELECT trigger_name, event_manipulation, event_object_table
    FROM information_schema.triggers
    WHERE trigger_schema = 'public'
    ORDER BY event_object_table, trigger_name;
  `;

  const result = await client.query(triggerQuery);
  
  if (result.rows.length > 0) {
    console.log('   Found triggers:');
    for (const row of result.rows) {
      console.log(`   - ${row.trigger_name} (${row.event_manipulation} on ${row.event_object_table})`);
    }
  } else {
    console.log('   ⚠️  No triggers found (append-only enforcement may not be active)');
  }

  await client.end();
}

// Main execution
async function main() {
  const postgresOk = await checkPostgres();
  if (!postgresOk) {
    process.exit(1);
  }

  await runMigrations();
  await verifyRolePermissions();
  await verifyTriggers();

  console.log('');
  console.log('='.repeat(70));
  console.log('Setup Complete!');
  console.log('='.repeat(70));
  console.log('');
  console.log('Next steps:');
  console.log('');
  console.log('1. Start the API server:');
  console.log('   npm start');
  console.log('');
  console.log('2. Create test users (in another terminal):');
  console.log('   node scripts/create-test-users.js');
  console.log('');
  console.log('3. Run verification tests:');
  console.log('   node scripts/verify-system.js');
  console.log('');
}

main().catch(err => {
  console.error('Setup failed:', err);
  process.exit(1);
});

